name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Check Python and ensurepip
        run: |
            where python
            python --version
            python -m ensurepip --version
      - name: Remove old venv
        run: if (Test-Path venv) { Remove-Item -Recurse -Force venv }
      - name: Set up venv
        run: python3 -m venv venv
      - name: Upgrade pip in venv
        run:
          venv\Scripts\python -m ensurepip --upgrade || (
            echo "ensurepip failed, installing pip manually" &&
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&
            venv\Scripts\python get-pip.py
          )
      - name: Install dependencies in venv
        run: venv\Scripts\pip install --no-user -r docker/requirements.txt
      - name: Run tests
        run: venv\Scripts\python -m pytest tests

  build-and-push:
    needs: test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/strinder-faceid:latest